=== ppotepa/fpv_fsim/assets/schemas/entity.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://fpv-fsim.dev/schemas/entity"
           xmlns:tns="http://fpv-fsim.dev/schemas/entity"
           elementFormDefault="qualified">

  <!-- Root element: entity -->
  <xs:element name="entity">
    <xs:complexType>
      <xs:sequence>
        <!-- Basic entity information -->
        <xs:element name="info" type="tns:EntityInfoType"/>

        <!-- Transform component (required) -->
        <xs:element name="transform" type="tns:TransformType"/>

        <!-- Optional components -->
        <xs:element name="renderable" type="tns:RenderableType" minOccurs="0"/>
        <xs:element name="physics" type="tns:PhysicsType" minOccurs="0"/>
        <xs:element name="vehicle" type="tns:VehicleType" minOccurs="0"/>
        <xs:element name="audio" type="tns:AudioType" minOccurs="0"/>
        <xs:element name="light" type="tns:LightType" minOccurs="0"/>

        <!-- Custom properties (support both property elements) -->
        <xs:choice minOccurs="0">
          <xs:element name="properties" type="tns:PropertiesType"/>
          <xs:element name="customProperties" type="tns:PropertiesType"/>
        </xs:choice>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
      <xs:attribute name="type" type="xs:string" use="required"/>
      <xs:attribute name="template" type="xs:string"/>
    </xs:complexType>
  </xs:element>

  <!-- Entity Info Type -->
  <xs:complexType name="EntityInfoType">
    <xs:sequence>
      <!-- Support both 'name' and 'n' for backward compatibility -->
      <xs:choice>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="n" type="xs:string"/>
      </xs:choice>
      <xs:element name="description" type="xs:string" minOccurs="0"/>
      <xs:element name="tags" type="tns:TagsType" minOccurs="0"/>
      <xs:element name="active" type="xs:boolean" minOccurs="0" default="true"/>
      <xs:element name="lifetime" type="xs:float" minOccurs="0" default="-1"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Tags Type -->
  <xs:complexType name="TagsType">
    <xs:sequence>
      <xs:element name="tag" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Transform Type -->
  <xs:complexType name="TransformType">
    <xs:sequence>
      <xs:element name="position" type="tns:Vector3Type" minOccurs="0"/>
      <xs:element name="rotation" type="tns:QuaternionType" minOccurs="0"/>
      <xs:element name="scale" type="tns:Vector3Type" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Vector3 Type -->
  <xs:complexType name="Vector3Type">
    <xs:attribute name="x" type="xs:float" default="0.0"/>
    <xs:attribute name="y" type="xs:float" default="0.0"/>
    <xs:attribute name="z" type="xs:float" default="0.0"/>
  </xs:complexType>

  <!-- Quaternion Type -->
  <xs:complexType name="QuaternionType">
    <xs:attribute name="x" type="xs:float" default="0.0"/>
    <xs:attribute name="y" type="xs:float" default="0.0"/>
    <xs:attribute name="z" type="xs:float" default="0.0"/>
    <xs:attribute name="w" type="xs:float" default="1.0"/>
  </xs:complexType>

  <!-- Renderable Component Type -->
  <xs:complexType name="RenderableType">
    <xs:sequence>
      <xs:element name="mesh" type="xs:string"/>
      <xs:element name="material" type="xs:string"/>
      <xs:element name="visible" type="xs:boolean" minOccurs="0" default="true"/>
      <xs:element name="opacity" type="xs:float" minOccurs="0" default="1.0"/>
      <xs:element name="layer" type="xs:int" minOccurs="0" default="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Physics Component Type -->
  <xs:complexType name="PhysicsType">
    <xs:sequence>
      <xs:element name="enabled" type="xs:boolean" minOccurs="0" default="true"/>
      <xs:element name="mass" type="xs:float" minOccurs="0" default="1.0"/>
      <xs:element name="friction" type="xs:float" minOccurs="0" default="0.5"/>
      <xs:element name="restitution" type="xs:float" minOccurs="0" default="0.3"/>
      <xs:element name="collider-size" type="tns:Vector3Type" minOccurs="0"/>
      <xs:element name="kinematic" type="xs:boolean" minOccurs="0" default="false"/>
      <xs:element name="use-gravity" type="xs:boolean" minOccurs="0" default="true"/>
      <xs:element name="collider-type" minOccurs="0" default="sphere">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="sphere"/>
            <xs:enumeration value="box"/>
            <xs:enumeration value="capsule"/>
            <xs:enumeration value="mesh"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Vehicle Component Type -->
  <xs:complexType name="VehicleType">
    <xs:sequence>
      <xs:element name="type" minOccurs="0" default="drone">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="drone"/>
            <xs:enumeration value="aircraft"/>
            <xs:enumeration value="helicopter"/>
            <xs:enumeration value="rocket"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="max-speed" type="xs:float" minOccurs="0" default="100.0"/>
      <xs:element name="acceleration" type="xs:float" minOccurs="0" default="10.0"/>
      <xs:element name="maneuverability" type="xs:float" minOccurs="0" default="5.0"/>
      <xs:element name="controller-type" minOccurs="0" default="manual">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="manual"/>
            <xs:enumeration value="autopilot"/>
            <xs:enumeration value="waypoint"/>
            <xs:enumeration value="follow"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>

  <!-- Audio Component Type -->
  <xs:complexType name="AudioType">
    <xs:sequence>
      <!-- Support both 'sound-id' and 'sound' for backward compatibility -->
      <xs:choice>
        <xs:element name="sound-id" type="xs:string"/>
        <xs:element name="sound" type="xs:string"/>
      </xs:choice>
      <xs:element name="volume" type="xs:float" minOccurs="0" default="1.0"/>
      <xs:element name="loop" type="xs:boolean" minOccurs="0" default="false"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Light Component Type -->
  <xs:complexType name="LightType">
    <xs:sequence>
      <xs:element name="type" minOccurs="0" default="point">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="point"/>
            <xs:enumeration value="directional"/>
            <xs:enumeration value="spot"/>
            <xs:enumeration value="area"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="color" type="tns:ColorType"/>
      <xs:element name="intensity" type="xs:float" minOccurs="0" default="1.0"/>
      <xs:element name="range" type="xs:float" minOccurs="0" default="10.0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Color Type -->
  <xs:complexType name="ColorType">
    <xs:attribute name="r" type="xs:float" default="1.0"/>
    <xs:attribute name="g" type="xs:float" default="1.0"/>
    <xs:attribute name="b" type="xs:float" default="1.0"/>
    <xs:attribute name="a" type="xs:float" default="1.0"/>
  </xs:complexType>

  <!-- Custom Properties Type -->
  <xs:complexType name="PropertiesType">
    <xs:sequence>
      <xs:element name="property" minOccurs="0" maxOccurs="unbounded">
        <xs:complexType>
          <xs:simpleContent>
            <xs:extension base="xs:string">
              <xs:attribute name="name" type="xs:string" use="required"/>
              <xs:attribute name="type" type="xs:string" default="string"/>
            </xs:extension>
          </xs:simpleContent>
        </xs:complexType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ppotepa/fpv_fsim/assets/entities/simple_drone.xml
<?xml version="1.0" encoding="UTF-8"?>
<entity id="simple_drone" type="vehicle" 
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="../schemas/entity.xsd">
    
    <info>
        <name>Simple Test Drone</name>
        <description>A simple drone entity for testing XML loading</description>
        <tags>
            <tag>test</tag>
            <tag>drone</tag>
            <tag>vehicle</tag>
        </tags>
        <active>true</active>
        <lifetime>-1</lifetime>
    </info>
    
    <transform>
        <position x="0.0" y="10.0" z="0.0"/>
        <rotation x="0.0" y="0.0" z="0.0" w="1.0"/>
        <scale x="1.0" y="1.0" z="1.0"/>
    </transform>
    
    <renderable>
        <mesh>drone_basic</mesh>
        <material>drone_material</material>
        <visible>true</visible>
        <opacity>1.0</opacity>
        <layer>0</layer>
    </renderable>
    
    <physics>
        <enabled>true</enabled>
        <mass>1.5</mass>
        <friction>0.5</friction>
        <restitution>0.2</restitution>
        <collider-size x="0.5" y="0.2" z="0.5"/>
        <kinematic>false</kinematic>
        <use-gravity>true</use-gravity>
        <collider-type>box</collider-type>
    </physics>
    
    <vehicle>
        <type>drone</type>
        <max-speed>30.0</max-speed>
        <acceleration>5.0</acceleration>
        <maneuverability>8.0</maneuverability>
        <controller-type>manual</controller-type>
    </vehicle>
    
    <audio>
        <sound-id>drone_engine</sound-id>
        <volume>0.8</volume>
        <loop>true</loop>
    </audio>
    
    <light>
        <type>point</type>
        <color r="1.0" g="0.8" b="0.2" a="1.0"/>
        <intensity>0.8</intensity>
        <range>5.0</range>
    </light>
    
    <properties>
        <property name="max_flight_time" type="float">15.0</property>
        <property name="battery_level" type="float">100.0</property>
        <property name="model_name" type="string">Explorer Pro</property>
    </properties>
</entity>
